;system styles
[RULER]
Family=Times New Roman
Size=10
Bold=false
Italic=false
Underline=false
StrikeOut=false
HQ=true
Color=201,202,203
ShadowX=
ShadowY=
ShadowColor=
OutlineThickness=
OutlineColor=
3DColor=
3DDepth=
3DStepX=
3DStepY=