--[[!
@fqxn Dox.Builders.HTML.Data.HTML
@des The core HTML code that is modified by the builder when creating the final HTML document.
!]]
return [[
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${__DOX__TITLE__} Documentation</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <style>
        ${__DOX__CSS__}
    </style>

    ${__DOX__PRISM_CSS__}

</head>
<body>
    <header id="titlebg">
        <div class="dox-brand">DOX <span>PROJECT REFERENCE</span></div>
        <h1 id="title">${__DOX__TITLE__}</h1>
        <p class="dox-subtitle">Documentation generated by LuaEx</p>
    </header>

    <div id="DOX_breadcrumb-wrapper">
        <nav aria-label="Your location"><ol id="DOX_breadcrumb" class="breadcrumb"></ol></nav>
    </div>

    <div class="dox-workspace">
        <aside id="DOX_navmenu_wrapper" aria-label="Documentation topics">
            <h2 id="DOX_navheading">Project reference</h2>
            <ul id="DOX_navmenu" class="nav flex-column"></ul>
        </aside>
        <main id="DOX_content_wrapper">
            <div class="dox-topic-header">
                <p id="DOX_location"></p>
                <h2 id="DOX_topic"></h2>
            </div>
            <div id="DOX_content"></div>
        </main>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    ${__DOX__PRISM__SCRIPTS__}

    <!-- Instantiate Dox and update the page -->
    <script>
        ${__DOX__INTERNAL_JS__}

    function bootDox() {
        const oDox = new Dox();
        oDox.updatePage(false);
    }

    if (window.Prism) {
        bootDox();
    } else {
        window.addEventListener('load', bootDox);
    }
    </script>
</body>
</html>
]];
