local class     = class;
local enum      = enum;
local math      = math;
local type      = type;
local Protean   = Protean;

-- Runtime binding records are weak: they must not keep discarded trackers alive.
local _tXPBindings = setmetatable({}, {__mode = "k"});


local function validateNumber(nValue, nMinimum, bInteger)
    type.assert.number(nValue);
    assert(nValue == nValue and nValue > -math.huge and nValue < math.huge,
           "XPSystem values must be finite.");
    assert(nValue >= nMinimum, "XPSystem value is below its minimum.");
    assert(not bInteger or nValue % 1 == 0, "XPSystem value must be an integer.");
end


local function calculateBounds(eType, nLevelOneXP, nMaxLevel, nProgression, nStepSize)
    type.assert.custom(eType, "XPSystem.TYPE");
    validateNumber(nLevelOneXP, 1, false);
    validateNumber(nMaxLevel, 1, true);
    validateNumber(nProgression, eType == XPSystem.TYPE.EXPONENTIAL and 1 or 0, false);
    validateNumber(nStepSize, 1, true);

    local tBounds   = {[0] = 0};
    local nTotal    = 0;
    local eTypes    = XPSystem.TYPE;

    for nLevel = 1, nMaxLevel do
        local nOffset = nLevel - 1;
        local nCost   = nLevelOneXP;

        -- Offset zero guarantees every curve starts at the supplied level-one cost.
        if (eType == eTypes.LINEAR) then
            nCost = nLevelOneXP + nProgression * nOffset;

        elseif (eType == eTypes.LOGARITHMIC) then
            nCost = nLevelOneXP + nProgression * math.log(nLevel);

        elseif (eType == eTypes.EXPONENTIAL) then
            nCost = nLevelOneXP * nProgression ^ nOffset;

        elseif (eType == eTypes.QUADRATIC) then
            nCost = nLevelOneXP + nProgression * nOffset ^ 2;

        elseif (eType == eTypes.CUBIC) then
            nCost = nLevelOneXP + nProgression * nOffset ^ 3;

        elseif (eType == eTypes.STEP) then
            nCost = nLevelOneXP + nProgression * math.floor(nOffset / nStepSize);
        end

        -- Round each level's cost, then accumulate it. Never round the running formula.
        nCost = math.ceil(nCost);
        local nNextTotal = nTotal + nCost;
        assert(nNextTotal < math.huge and nNextTotal > nTotal,
               "XPSystem thresholds overflow or cannot represent distinct levels.");

        nTotal = nNextTotal;
        tBounds[nLevel] = nTotal;
    end

    return tBounds;
end


local function updateLevel(this, cdat, bNotify)
    local pri       = cdat.pri;
    local pro       = cdat.pro;
    local nFinalXP  = pro.XPProtean.getValue();
    local nOldLevel = pro.Level;
    local nNewLevel = 0;

    -- Binary search handles gaining or losing many levels in one XP change.
    local nLow  = 1;
    local nHigh = pri.levelBoundsCount;

    while (nLow <= nHigh) do
        local nMiddle = math.floor((nLow + nHigh) / 2);

        if (nFinalXP >= pri.levelBounds[nMiddle]) then
            nNewLevel = nMiddle;
            nLow = nMiddle + 1;
        else
            nHigh = nMiddle - 1;
        end
    end

    -- Commit the level before calling user code, so callbacks see the new state.
    pro.Level = nNewLevel;

    if (bNotify and nOldLevel ~= nNewLevel and pri.IsCallbackActive) then
        pri.onChange(this, nOldLevel, nNewLevel, nFinalXP);
    end
end


local function placeholder() end


local function snapshotXP(oProtean)
    -- Use autogenerated state to preserve active limits and manual cached values.
    -- Detach links and notifications so a probe or copy cannot affect the source.
    local tState   = deserialize(rawgetmetatable(oProtean).__serialize());
    local tPrivate = tState.Protean.pri;

    tPrivate.values[Protean.VALUE_BASE] = oProtean.getValue(Protean.VALUE_BASE);
    tPrivate.isLinked                  = false;
    tPrivate.linkerID                  = -1;
    tPrivate.isCallbackActive          = false;

    return Protean.deserialize(tState);
end


local function bindXP(this, cdat)
    local pri       = cdat.pri;
    local pro       = cdat.pro;
    local oProtean  = pro.XPProtean;

    if (_tXPBindings[this] ~= oProtean) then
        -- Autogenerated class restoration does not run constructors. Reconnect the
        -- internal callback through a fresh Protean using its autogenerated state.
        -- This preserves modifiers, limits, cached/manual values, and link state.
        -- The state layout belongs to the current Protean/class implementation;
        -- revisit this binding if that autogenerated layout changes.
        local tState = deserialize(rawgetmetatable(oProtean).__serialize());
        local tPrivate = tState.Protean.pri;
        tPrivate.isCallbackLocked       = false;
        tPrivate.isCallbackToggleLocked = false;

        oProtean = Protean.deserialize(tState);
        oProtean.setCallback(function()
            updateLevel(this, cdat, true);
        end);
        oProtean.lockCallback();
        oProtean.lockCallbackToggle();

        pro.XPProtean = oProtean;
        _tXPBindings[this] = oProtean;

        -- User callbacks are runtime behavior, not restored closures. Cloning
        -- deliberately reinstates the original callback after this binding step.
        pri.onChange         = placeholder;
        pri.IsCallbackActive = false;
    end
end


local function changeSetting(this, cdat, sField, vValue, bSkipUpdate)
    local pri = cdat.pri;
    assert(bSkipUpdate == nil or type(bSkipUpdate) == "boolean", "Skip-update flag must be boolean.");

    local tValues = {
        Type = XPSystem.TYPE[pri.Type], levelOneXP = pri.levelOneXP, MaxLevel = pri.MaxLevel,
        Progression = pri.Progression, StepSize = pri.StepSize,
    };
    tValues[sField] = vValue;

    -- Validate and build the complete candidate before changing the live settings.
    local tBounds = calculateBounds(tValues.Type, tValues.levelOneXP, tValues.MaxLevel,
                                    tValues.Progression, tValues.StepSize);
    bindXP(this, cdat);

    pri[sField]          = sField == "Type" and vValue.name or vValue;
    pri.levelBounds     = tBounds;
    pri.levelBoundsCount = tValues.MaxLevel;

    if not (bSkipUpdate) then
        updateLevel(this, cdat, true);
    end

    return this;
end


--[[!
    @fqxn CoG.XPSystem
    @desc An experience tracker and leveling system. Every curve calculates the
    XP cost of gaining one level. Rounded-up costs accumulate into total thresholds;
    earned XP is cumulative and is not spent when gaining levels. Level zero starts
    at zero XP. Levels cap at MaxLevel, while surplus XP is retained.
!]]
return class("XPSystem",
{--METAMETHODS
    __clone = function(this, cdat)
        bindXP(this, cdat);

        local pri   = cdat.pri;
        local oCopy = XPSystem(XPSystem.TYPE[pri.Type], pri.levelOneXP, pri.MaxLevel, pri.Progression, pri.StepSize);
        local tCopy = cdat.ins[oCopy];

        -- Clone the Protean snapshot, then give the copy its own callback owner.
        tCopy.pro.XPProtean = snapshotXP(cdat.pro.XPProtean);
        bindXP(oCopy, tCopy);
        updateLevel(oCopy, tCopy, false);

        tCopy.pri.onChange               = pri.onChange;
        tCopy.pri.IsCallbackActive       = pri.IsCallbackActive;
        tCopy.pri.IsCallbackLocked       = pri.IsCallbackLocked;
        tCopy.pri.IsCallbackToggleLocked = pri.IsCallbackToggleLocked;

        return oCopy;
    end,
},
{--STATIC PUBLIC
    --[[!
        @fqxn CoG.XPSystem.Enums.TYPE
        @desc Dictates the mathematical mechanisms used to calculate experience
        cost per level. Let B be level-one cost, P progression, L the destination
        level, and S step size. Each cost is rounded up before accumulation.
        <ul>
            <li><b>LINEAR</b>: B + P * (L - 1)</li>
            <li><b>LOGARITHMIC</b>: B + P * log(L), using the natural logarithm</li>
            <li><b>EXPONENTIAL</b>: B * P^(L - 1), with P at least 1</li>
            <li><b>QUADRATIC</b>: B + P * (L - 1)^2</li>
            <li><b>CUBIC</b>: B + P * (L - 1)^3</li>
            <li><b>STEP</b>: B + P * floor((L - 1) / S)</li>
        </ul>
    !]]
    TYPE = enum("XPSystem.TYPE", {"LINEAR", "LOGARITHMIC", "EXPONENTIAL", "QUADRATIC", "CUBIC", "STEP"}, nil, true),
},
{--PRIVATE
    levelOneXP                      = 1,
    levelBounds                     = {},
    levelBoundsCount                = 0,
    MaxLevel__autoAF                 = 1,
    onChange                        = placeholder,
    IsCallbackActive                = false,
    IsCallbackLocked__autoAF         = false,
    IsCallbackToggleLocked__autoAF   = false,
    Progression__autoAF              = 0,
    StepSize__autoAF                 = 2,
    -- Store the enum member name so autogenerated serialization needs no nested enum restoration.
    Type                            = "LINEAR",
},
{--PROTECTED
    Level       = 0,
    XPProtean   = null,
},
{--PUBLIC
    --[[!
    @fqxn CoG.XPSystem.Methods.XPSystem
    @desc Creates a tracker. Level-one cost is at least 1; maximum level and step
    size are positive integers. Progression is nonnegative, or at least 1 for
    exponential curves. All numbers must be finite. Step size defaults to 2.
    @param XPSystem.TYPE eType The curve.
    @param number nLevelOneXP The cost to reach level one.
    @param number nMaxLevel The maximum level.
    @param number nProgression The curve's increment or exponential multiplier.
    @param number|nil nStepSize The levels per step.
    !]]
    XPSystem = function(this, cdat, eType, nLevelOneXP, nMaxLevel, nProgression, nStepSize)
        local pri = cdat.pri;
        nStepSize = nStepSize == nil and 2 or nStepSize;

        local tBounds = calculateBounds(eType, nLevelOneXP, nMaxLevel, nProgression, nStepSize);

        pri.Type             = eType.name;
        pri.levelOneXP       = nLevelOneXP;
        pri.MaxLevel         = nMaxLevel;
        pri.Progression      = nProgression;
        pri.StepSize         = nStepSize;
        pri.levelBounds      = tBounds;
        pri.levelBoundsCount = nMaxLevel;

        cdat.pro.XPProtean = Protean(0, 0, 0, 0, 0, 0, 0, 0);
        bindXP(this, cdat);
    end,

    -- Access through this method also reconnects tracking after class restoration.
    getXPProtean = function(this, cdat)
        bindXP(this, cdat);
        return cdat.pro.XPProtean;
    end,

    getLevel = function(this, cdat)
        bindXP(this, cdat);
        updateLevel(this, cdat, true);
        return cdat.pro.Level;
    end,

    getLevelOneXP = function(this, cdat)
        return cdat.pri.levelOneXP;
    end,

    getType = function(this, cdat)
        return XPSystem.TYPE[cdat.pri.Type];
    end,

    getIsCallbackActive = function(this, cdat)
        bindXP(this, cdat);
        return cdat.pri.IsCallbackActive;
    end,

    --[[!
    @fqxn CoG.XPSystem.Methods.refresh
    @desc Recalculates the level from current final XP, notifying on changes.
    Use after deferred setting updates or manual Protean calculation.
    @return XPSystem oSystem This object.
    !]]
    refresh = function(this, cdat)
        bindXP(this, cdat);
        updateLevel(this, cdat, true);
        return this;
    end,

    --[[!
    @fqxn CoG.XPSystem.Methods.getXPToLevel
    @desc Returns remaining XP for a level, clamped to zero if already reached.
    Returns -1 for a level above MaxLevel. Level zero is valid.
    @param number nLevel The nonnegative integer destination level.
    @return number nXP Remaining XP, or -1 if unavailable.
    !]]
    getXPToLevel = function(this, cdat, nLevel)
        validateNumber(nLevel, 0, true);
        bindXP(this, cdat);
        local nRet = -1;

        if (nLevel <= cdat.pri.levelBoundsCount) then
            nRet = math.max(0, cdat.pri.levelBounds[nLevel] - cdat.pro.XPProtean.getValue());
        end

        return nRet;
    end,

    --[[!
    @fqxn CoG.XPSystem.Methods.getXPToNextLevel
    @desc Returns remaining XP for the next level, or -1 at MaxLevel.
    @return number nXP Remaining XP, or -1 when there is no next level.
    !]]
    getXPToNextLevel = function(this, cdat)
        local nLevel = this.getLevel();
        return this.getXPToLevel(nLevel + 1);
    end,

    --[[!
    @fqxn CoG.XPSystem.Methods.getXPRequired
    @desc Returns the cumulative XP threshold for a nonnegative integer level.
    Returns -1 above MaxLevel; level zero requires zero XP.
    @param number nLevel The destination level.
    @return number nXP The total threshold, or -1 if unavailable.
    !]]
    getXPRequired = function(this, cdat, nLevel)
        validateNumber(nLevel, 0, true);
        local nRet = -1;

        if (nLevel <= cdat.pri.levelBoundsCount) then
            nRet = cdat.pri.levelBounds[nLevel];
        end

        return nRet;
    end,

    lockCallback = function(this, cdat)
        bindXP(this, cdat);
        cdat.pri.IsCallbackLocked = true;
        return this;
    end,

    lockCallbackToggle = function(this, cdat)
        bindXP(this, cdat);
        cdat.pri.IsCallbackToggleLocked = true;
        return this;
    end,

    setCallback = function(this, cdat, fCallback, bDoNotSetActive)
        bindXP(this, cdat);
        local pri = cdat.pri;
        assert(not pri.IsCallbackLocked, "XPSystem callback is locked.");
        assert(fCallback == nil or rawtype(fCallback) == "function", "Callback must be a function or nil.");
        assert(bDoNotSetActive == nil or type(bDoNotSetActive) == "boolean", "Callback activation flag must be boolean.");

        local bActive = rawtype(fCallback) == "function" and bDoNotSetActive ~= true;
        assert(not pri.IsCallbackToggleLocked or bActive == pri.IsCallbackActive,
               "XPSystem callback toggling is locked.");

        pri.onChange         = fCallback or placeholder;
        pri.IsCallbackActive = bActive;
        return this;
    end,

    setCallbackActive = function(this, cdat, bFlag)
        bindXP(this, cdat);
        local pri = cdat.pri;
        assert(not pri.IsCallbackToggleLocked, "XPSystem callback toggling is locked.");
        assert(bFlag == nil or type(bFlag) == "boolean", "Callback activation must be boolean.");

        pri.IsCallbackActive = bFlag == true and pri.onChange ~= placeholder;
        return this;
    end,

    --[[!
    @fqxn CoG.XPSystem.Methods.setLevel
    @desc Sets base XP so the final Protean value equals the requested level's
    threshold, accounting for modifiers. Rejects zero multipliers or active limits
    that prevent the requested value. Updates XP and level before notification.
    @param number nLevel The desired level, from zero through MaxLevel.
    @return XPSystem oSystem This object.
    !]]
    setLevel = function(this, cdat, nLevel)
        validateNumber(nLevel, 0, true);
        assert(nLevel <= cdat.pri.MaxLevel, "Level exceeds MaxLevel.");
        local oXP = this.getXPProtean();
        local nTarget = cdat.pri.levelBounds[nLevel];
        local nMultiplier = 1 + oXP.getValue(Protean.MULTIPLICATIVE_BONUS) - oXP.getValue(Protean.MULTIPLICATIVE_PENALTY);
        assert(nMultiplier ~= 0, "Cannot set level with a zero XP multiplier.");
        local nBase = (nTarget - oXP.getValue(Protean.ADDATIVE_BONUS) + oXP.getValue(Protean.ADDATIVE_PENALTY)) / nMultiplier
                      - oXP.getValue(Protean.BASE_BONUS) + oXP.getValue(Protean.BASE_PENALTY);
        validateNumber(nBase, -math.huge, false);

        -- Probe an independent snapshot before touching the live XP or callbacks.
        local oProbe = snapshotXP(oXP);
        oProbe.setValue(nBase);
        oProbe.calculateFinalValue();
        assert(oProbe.getValue() == nTarget, "XP limits prevent setting the requested level.");

        oXP.setValue(nBase);
        oXP.calculateFinalValue();
        updateLevel(this, cdat, true);
        return this;
    end,

    -- Setting methods build fresh bounds atomically. Skip-update defers only the
    -- level/callback refresh; the next XP change, getLevel(), or refresh() updates it.
    setMaxLevel = function(this, cdat, nValue, bSkipUpdate)
        return changeSetting(this, cdat, "MaxLevel", nValue, bSkipUpdate);
    end,

    setLevelOneXP = function(this, cdat, nValue, bSkipUpdate)
        return changeSetting(this, cdat, "levelOneXP", nValue, bSkipUpdate);
    end,

    setProgression = function(this, cdat, nValue, bSkipUpdate)
        return changeSetting(this, cdat, "Progression", nValue, bSkipUpdate);
    end,

    setStepInterval = function(this, cdat, nValue, bSkipUpdate)
        return changeSetting(this, cdat, "StepSize", nValue, bSkipUpdate);
    end,

    setStepSize = function(this, cdat, nValue, bSkipUpdate)
        return this.setStepInterval(nValue, bSkipUpdate);
    end,

    setType = function(this, cdat, eType, bSkipUpdate)
        return changeSetting(this, cdat, "Type", eType, bSkipUpdate);
    end,

    XPBoundsIterator = function(this, cdat)
        local nIndex  = 0;
        local nMax    = cdat.pri.levelBoundsCount;
        -- Retain the threshold snapshot so configuration changes cannot mix two
        -- different curves midway through this iterator.
        local tBounds = cdat.pri.levelBounds;

        return function()
            nIndex = nIndex + 1;

            if (nIndex <= nMax) then
                return nIndex, tBounds[nIndex];
            end
        end;
    end,
},
nil,   --extending class
false, --if the class is final
nil    --interface(s) (either nil, or interface(s))
);
